package strategy

import (
	"time"

	"github.com/shopspring/decimal"

	"money-loves-me/pkg/binance"
)

// StrategyParams is a map of parameter names to their decimal values.
type StrategyParams map[string]decimal.Decimal

// SignalDirection represents the direction of a trading signal.
type SignalDirection string

const (
	SignalBuy  SignalDirection = "BUY"
	SignalSell SignalDirection = "SELL"
)

// SignalReason captures the strategy decision context for a signal.
type SignalReason struct {
	Indicators  map[string]float64 `json:"indicators"`
	TriggerRule string             `json:"trigger_rule"`
	MarketState string             `json:"market_state"`
}

// Signal represents a trading signal generated by a strategy.
type Signal struct {
	Strategy       string          `json:"strategy"`
	Symbol         string          `json:"symbol"`
	Side           SignalDirection `json:"side"`
	Price          decimal.Decimal `json:"price"`
	Quantity       decimal.Decimal `json:"quantity"`
	ExpectedProfit decimal.Decimal `json:"expected_profit"` // expected profit before fees
	Reason         SignalReason    `json:"reason"`
	Timestamp      time.Time       `json:"timestamp"`
}

// FeeRate holds maker and taker fee rates.
type FeeRate struct {
	Maker decimal.Decimal
	Taker decimal.Decimal
}

// Strategy defines the interface that all trading strategies must implement.
type Strategy interface {
	// Name returns the strategy name.
	Name() string

	// Calculate analyzes klines and returns a trading signal, or nil if no signal.
	Calculate(klines []binance.Kline) *Signal

	// GetParams returns the current strategy parameters.
	GetParams() StrategyParams

	// SetParams updates the strategy parameters. Returns an error if params are invalid.
	SetParams(params StrategyParams) error

	// EstimateFee estimates the trading fee for a given price, quantity, and fee rate.
	EstimateFee(price, quantity, feeRate decimal.Decimal) decimal.Decimal
}
