package risk

import (
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/shopspring/decimal"
	"go.uber.org/zap"

	apperrors "money-loves-me/internal/errors"
	"money-loves-me/internal/logger"
	"money-loves-me/internal/model"
	"money-loves-me/internal/notification"
)

// StopLossSignal represents a stop-loss sell signal generated by the RiskManager.
type StopLossSignal struct {
	Symbol       string
	EntryPrice   decimal.Decimal
	CurrentPrice decimal.Decimal
	Quantity     decimal.Decimal
	LossPercent  decimal.Decimal
	Timestamp    time.Time
}

// StrategyPauser is the interface for pausing all running strategies.
type StrategyPauser interface {
	PauseAll() error
}

// AccountValuer provides total asset value for position ratio checks.
type AccountValuer interface {
	GetTotalAssetValue() (decimal.Decimal, error)
}

// RiskStore defines the persistence interface for risk configuration.
type RiskStore interface {
	Get() (*model.RiskConfig, error)
	Save(config *model.RiskConfig) error
}

// RiskConfig holds the in-memory risk control parameters.
type RiskConfig struct {
	MaxOrderAmount   decimal.Decimal            // max single order amount (USDT)
	MaxDailyLoss     decimal.Decimal            // max daily loss (USDT)
	StopLossPercent  map[string]decimal.Decimal // per-symbol stop-loss percentage
	MaxPositionRatio map[string]decimal.Decimal // per-symbol max position ratio
}

// RiskManager implements risk control checks for the trading system.
type RiskManager struct {
	config   RiskConfig
	store    RiskStore
	notifier *notification.NotificationService
	pauser   StrategyPauser
	log      *logger.Logger
	mu       sync.RWMutex
}

// NewRiskManager creates a new RiskManager with the given dependencies.
func NewRiskManager(
	store RiskStore,
	notifier *notification.NotificationService,
	pauser StrategyPauser,
	log *logger.Logger,
) *RiskManager {
	return &RiskManager{
		config: RiskConfig{
			StopLossPercent:  make(map[string]decimal.Decimal),
			MaxPositionRatio: make(map[string]decimal.Decimal),
		},
		store:    store,
		notifier: notifier,
		pauser:   pauser,
		log:      log,
	}
}

// logWarn safely logs at WARN level, handling nil logger.
func (rm *RiskManager) logWarn(msg string, fields ...zap.Field) {
	if rm.log != nil {
		rm.log.Warn(msg, fields...)
	}
}

// logInfo safely logs at INFO level, handling nil logger.
func (rm *RiskManager) logInfo(msg string, fields ...zap.Field) {
	if rm.log != nil {
		rm.log.Info(msg, fields...)
	}
}

// logError safely logs at ERROR level, handling nil logger.
func (rm *RiskManager) logError(msg string, fields ...zap.Field) {
	if rm.log != nil {
		rm.log.Error(msg, fields...)
	}
}

// GetConfig returns a copy of the current risk configuration.
func (rm *RiskManager) GetConfig() RiskConfig {
	rm.mu.RLock()
	defer rm.mu.RUnlock()
	return rm.copyConfig()
}

// SetConfig updates the in-memory risk configuration.
func (rm *RiskManager) SetConfig(cfg RiskConfig) {
	rm.mu.Lock()
	defer rm.mu.Unlock()
	rm.config = cfg
}

// copyConfig returns a deep copy of the current config (caller must hold lock).
func (rm *RiskManager) copyConfig() RiskConfig {
	slp := make(map[string]decimal.Decimal, len(rm.config.StopLossPercent))
	for k, v := range rm.config.StopLossPercent {
		slp[k] = v
	}
	mpr := make(map[string]decimal.Decimal, len(rm.config.MaxPositionRatio))
	for k, v := range rm.config.MaxPositionRatio {
		mpr[k] = v
	}
	return RiskConfig{
		MaxOrderAmount:   rm.config.MaxOrderAmount,
		MaxDailyLoss:     rm.config.MaxDailyLoss,
		StopLossPercent:  slp,
		MaxPositionRatio: mpr,
	}
}

// CheckOrder validates whether an order is allowed by risk rules.
// It checks: (1) amount <= MaxOrderAmount, (2) position ratio <= MaxPositionRatio.
func (rm *RiskManager) CheckOrder(symbol string, amount, totalAssetValue decimal.Decimal) error {
	rm.mu.RLock()
	defer rm.mu.RUnlock()

	// Check single order amount limit.
	if rm.config.MaxOrderAmount.IsPositive() && amount.GreaterThan(rm.config.MaxOrderAmount) {
		rm.logWarn("order rejected: exceeds max order amount",
			zap.String("symbol", symbol),
			zap.String("amount", amount.String()),
			zap.String("limit", rm.config.MaxOrderAmount.String()),
		)
		return apperrors.NewAppError(apperrors.ErrRiskControl,
			fmt.Sprintf("order amount %s exceeds max order amount %s",
				amount.String(), rm.config.MaxOrderAmount.String()),
			"risk", nil)
	}

	// Check position ratio limit.
	if maxRatio, ok := rm.config.MaxPositionRatio[symbol]; ok && maxRatio.IsPositive() {
		if totalAssetValue.IsPositive() {
			ratio := amount.Div(totalAssetValue)
			if ratio.GreaterThan(maxRatio) {
				rm.logWarn("order rejected: exceeds max position ratio",
					zap.String("symbol", symbol),
					zap.String("ratio", ratio.String()),
					zap.String("limit", maxRatio.String()),
				)
				return apperrors.NewAppError(apperrors.ErrRiskControl,
					fmt.Sprintf("position ratio %s exceeds max position ratio %s for %s",
						ratio.String(), maxRatio.String(), symbol),
					"risk", nil)
			}
		}
	}

	return nil
}

// CheckDailyLoss calculates today's cumulative loss (including fees) from the
// given trades and returns whether strategies should be paused.
func (rm *RiskManager) CheckDailyLoss(trades []model.Trade) (shouldPause bool, dailyLoss decimal.Decimal) {
	rm.mu.RLock()
	maxDailyLoss := rm.config.MaxDailyLoss
	rm.mu.RUnlock()

	now := time.Now()
	startOfDay := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, now.Location())

	dailyLoss = decimal.Zero
	for _, t := range trades {
		if t.ExecutedAt.Before(startOfDay) {
			continue
		}
		// For SELL trades, profit = amount - fee (positive means gain).
		// For BUY trades, cost = amount + fee (negative means spending).
		// Net daily PnL: sum of (sell amounts - buy amounts - all fees).
		switch t.Side {
		case "SELL":
			dailyLoss = dailyLoss.Sub(t.Amount) // selling adds revenue (reduces loss)
		case "BUY":
			dailyLoss = dailyLoss.Add(t.Amount) // buying adds cost (increases loss)
		}
		dailyLoss = dailyLoss.Add(t.Fee) // fees always increase loss
	}

	// dailyLoss > 0 means net loss; dailyLoss < 0 means net gain.
	if maxDailyLoss.IsPositive() && dailyLoss.GreaterThanOrEqual(maxDailyLoss) {
		return true, dailyLoss
	}

	return false, dailyLoss
}

// GenerateStopLossSignal checks if a position's loss has reached the stop-loss
// threshold and returns a stop-loss sell signal if so. Returns nil if no signal.
func (rm *RiskManager) GenerateStopLossSignal(
	symbol string,
	entryPrice, currentPrice, quantity decimal.Decimal,
) *StopLossSignal {
	rm.mu.RLock()
	stopLossPct, ok := rm.config.StopLossPercent[symbol]
	rm.mu.RUnlock()

	if !ok || !stopLossPct.IsPositive() {
		return nil
	}

	if entryPrice.IsZero() {
		return nil
	}

	// lossPercent = (entryPrice - currentPrice) / entryPrice * 100
	// Positive lossPercent means the price dropped (loss).
	lossPercent := entryPrice.Sub(currentPrice).Div(entryPrice).Mul(decimal.NewFromInt(100))

	if lossPercent.GreaterThanOrEqual(stopLossPct) {
		rm.logWarn("stop-loss signal generated",
			zap.String("symbol", symbol),
			zap.String("lossPercent", lossPercent.String()),
			zap.String("threshold", stopLossPct.String()),
		)
		return &StopLossSignal{
			Symbol:       symbol,
			EntryPrice:   entryPrice,
			CurrentPrice: currentPrice,
			Quantity:     quantity,
			LossPercent:  lossPercent,
			Timestamp:    time.Now(),
		}
	}

	return nil
}

// PauseAllStrategies pauses all running strategies and sends a risk alert notification.
func (rm *RiskManager) PauseAllStrategies() error {
	rm.logWarn("pausing all strategies due to risk control trigger")

	if rm.pauser != nil {
		if err := rm.pauser.PauseAll(); err != nil {
			rm.logError("failed to pause strategies", zap.Error(err))
			return apperrors.NewAppError(apperrors.ErrRiskControl,
				"failed to pause strategies", "risk", err)
		}
	}

	if rm.notifier != nil {
		_ = rm.notifier.Send(
			notification.EventRiskAlert,
			"All strategies paused",
			"Risk control triggered: all running strategies have been paused. Please review your risk settings and market conditions.",
		)
	}

	return nil
}

// SaveConfig persists the current in-memory risk configuration to the database.
func (rm *RiskManager) SaveConfig() error {
	rm.mu.RLock()
	cfg := rm.copyConfig()
	rm.mu.RUnlock()

	slpJSON, err := json.Marshal(cfg.StopLossPercent)
	if err != nil {
		return apperrors.NewAppError(apperrors.ErrDatabase,
			"failed to marshal stop loss percents", "risk", err)
	}

	mprJSON, err := json.Marshal(cfg.MaxPositionRatio)
	if err != nil {
		return apperrors.NewAppError(apperrors.ErrDatabase,
			"failed to marshal max position percents", "risk", err)
	}

	dbConfig := &model.RiskConfig{
		MaxOrderAmount:      cfg.MaxOrderAmount,
		MaxDailyLoss:        cfg.MaxDailyLoss,
		StopLossPercents:    slpJSON,
		MaxPositionPercents: mprJSON,
	}

	if err := rm.store.Save(dbConfig); err != nil {
		return apperrors.NewAppError(apperrors.ErrDatabase,
			"failed to save risk config", "risk", err)
	}

	rm.logInfo("risk config saved to database")
	return nil
}

// LoadConfig loads the risk configuration from the database into memory.
func (rm *RiskManager) LoadConfig() error {
	dbConfig, err := rm.store.Get()
	if err != nil {
		return apperrors.NewAppError(apperrors.ErrDatabase,
			"failed to load risk config", "risk", err)
	}

	var slp map[string]decimal.Decimal
	if err := json.Unmarshal(dbConfig.StopLossPercents, &slp); err != nil {
		return apperrors.NewAppError(apperrors.ErrDatabase,
			"failed to unmarshal stop loss percents", "risk", err)
	}

	var mpr map[string]decimal.Decimal
	if err := json.Unmarshal(dbConfig.MaxPositionPercents, &mpr); err != nil {
		return apperrors.NewAppError(apperrors.ErrDatabase,
			"failed to unmarshal max position percents", "risk", err)
	}

	rm.mu.Lock()
	rm.config = RiskConfig{
		MaxOrderAmount:   dbConfig.MaxOrderAmount,
		MaxDailyLoss:     dbConfig.MaxDailyLoss,
		StopLossPercent:  slp,
		MaxPositionRatio: mpr,
	}
	rm.mu.Unlock()

	rm.logInfo("risk config loaded from database")
	return nil
}
